mpi:
  - nompi
  - mpich  # [unix]
  - openmpi  # [unix]
  - msmpi # [win]

fortran_compiler:   # [win]
    - ifx           # [win]

fortran_compiler_version:   # [win]
    - '2025.*'              # [win]
impi_devel:                 # [win]
  - 2021.17                 # [win]
