{% set name = "libmed" %}
{% set version = "3.3.1" %}
{% set sha256 = "dd631ef813838bc7413ff0dd6461d7a0d725bcfababdf772ece67610a8d22588" %}


package:
    name: libmed
    version: 3.3.1

source:
    fn: {{ name }} {{ version }}.tar.gz
    url: http://files.salome-platform.org/Salome/other/med-{{ version }}.tar.gz
    sha256: {{ sha256  }}

    patches:
        - swig.patch

build:
    number: 1002
    skip: true  # [py<35]

requirements:
    build:
        - ninja
        - cmake
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - hdf5 1.8*
        - zlib
        - python
        - swig
    run:
        - hdf5
        - zlib
        - python


test:
    imports:
        - med

about:
    home: http://www.salome-platform.org/
    license: LGPLv3.0
    license_family: LGPL
    license_file: COPYING
    summary: geometry mesh formats
    description: import / export of med-files (please give us more information)
    doc_url: http://www.salome-platform.org/
    dev_url: http://www.salome-platform.org/

extra:
    recipe-maintainers:
        - looooo
