# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxfortran_compilergfortranpython3.6
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxfortran_compilergfortranpython3.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_fortpython3.6
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_fortpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Cze0I8XFvcz6dCuavVDqBH/Qjho6W7C4Hm6hteSu7ylRRFkF+gaHX+4aA6Dalx6OIDD69QmOzd1BAozZUbTEYVW9iYFq6Gw0y7BEzECtruhB1vrCD2vRbdULs9P+f8fkn+ZUJrEhXAjkdV+z0DsYbr+aB3TWzK0Gyo5t5P26gmcnG6UNqK2dgdcDGO2xpfs+jCmhchICkUWC5vCFhY/HXd60C+Z7jvLpuLDlMmDMi3mjWXcJVhjgwXhWS1Ppi6m7faY6Y4emhaXtS4IfQ0FmGfr2lp+mGHZJWsyMry7TzcAjJfAb9ikoRGx8QOfJIQarp7YhMXMRFlBnzAlNVL/JV4YozMju9rqGKshfgt5DFyTpDXz0igfJkl8/xKZo+oF4TLMiiXgJ38/3cdPFQU4DVIhJGr5SIq4wkgQ2tU15XEJ6CeybfwzJfdx5bAKJvXFQHBqyf5UwVg85FJ7Pnltep+djpRZl5ELbcAKOL8E+bsx9r2ds1oipflvW/0XXBAhBk1H/AQmvNjpal2TDHAKxvGF/Mxxk4yzWRWXgqyR17qBotxW9i3x1D+++dcKQAg3R63YlpQCowmcSGcyYvyjIUkbCbgzKdRfnMwoT0ZIfLd5kZL91eXyiHLXyuFyrKB50PdaIezx6eyPL9+18ZDdeLmpDubGGhGsDvcIzmsebkXA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml